version: "3.9"

services:
  docask:
    build: .
    container_name: docask-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    restart: always
